### ISSUE TITLE
Any way to run it on docker-compose.yml and traefik?

### ISSUE THREAD

**Issue by thepenguinthatwants** [xataz/docker-lufi#14]
I tried to run it but it didnt seem to work.

```
version: '3'
services:

  lufi:
    image: xataz/lufi
    networks:
      - srv
    ports:
      - "8083:8080"
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:lufi.localhost"
      - traefik.port=80

networks:
  srv:
    external: true
```

**Comment by xataz** [comment]
Hi,

```
version: '3'
services:

  lufi:
    image: xataz/lufi
    networks:
      - srv
    ports:
      - "8083:8080"
    labels:
      - traefik.enable=true
      - "traefik.frontend.rule=Host:lufi.localhost"
      - traefik.port=8080

networks:
  srv:
    external: true
```
